# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Lets roll
        id: lets_roll
        run: |
          git config --global user.email "axonasif@gmail.com"
          git config --global user.name "AXIM0S"
          
          rm -r .github
          
          for rolls in {1..696965}; do
            echo -e "# 69\n${RANDOM}" > README.md
            git commit -a -m "We have frikin rolled $rolls times"
          done
          
          echo "# 69" > README.md
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: AXIM0S
          author_email: axonasif@gmail.com
          message: 'We have frikin rolled 69696969 times. Mission passed, RESPEC++'
          add: './README.md'
